# Install: Manage basic resource setup, such as packages or service users.

---

- name: "Setup | Install | Default | Remove unwanted packages (e.g., to prevent conflicts or resolve incompatibilities)"
  ansible.builtin.package:
    name: "{{ __run_nginx_packages_removal }}"
    state: "absent"
  when:
    - __run_nginx_packages_removal is ansible.builtin.defined
    - (__run_nginx_packages_removal | ansible.builtin.length) > 0


- name: "Setup | Install | Default | Install or upgrade packages"
  ansible.builtin.package:
    name: "{{ __run_nginx_packages_install }}"
    state: "{{ 'latest' if run_nginx_autoupgrade else 'present' }}"
  when:
    - __run_nginx_packages_install is ansible.builtin.defined
    - (__run_nginx_packages_install | ansible.builtin.length) > 0


- name: "Setup | Install | Default | Show enabled modules requiring additional packages"
  ansible.builtin.debug:
    msg: >-
      {{
        run_nginx_modules_enabled
        | ansible.builtin.default([])
        | ansible.builtin.select('in', __run_nginx_modules_map_resources.keys() | list)
        | ansible.builtin.list
      }}
    verbosity: 4


- name: "Setup | Install | Default | Install module-specific packages"
  ansible.builtin.package:
    name: "{{ __run_nginx_modules_map_resources[item]['packages'] }}"
    state: "{{ 'latest' if run_nginx_autoupgrade else 'present' }}"
  when:
    - (__run_nginx_modules_map_resources[item]['packages'] | ansible.builtin.length) > 0
  loop: >-
    {{
      run_nginx_modules_enabled
      | ansible.builtin.default([])
      | ansible.builtin.select('in', __run_nginx_modules_map_resources.keys() | list)
      | ansible.builtin.list
    }}



- name: "Setup | Install | Default | Remove unwanted files and directories (e.g., to prevent conflicts or resolve incompatibilities)"
  ansible.builtin.file:
    path: "{{ item }}"
    state: "absent"
  when:
    - __run_nginx_paths_removal is ansible.builtin.defined
    - (__run_nginx_paths_removal | ansible.builtin.length) > 0
  loop: "{{ __run_nginx_paths_removal }}"
