# Internal role variables specific to: RedHat (os_family or distribution)
#
# Only values specific to the platform and its functionality should be included
# here. Variables in this file override those defined in vars/main.yml.

---

__run_nginx_module_so_lib_dir_path: "/usr/lib64/nginx/modules"


# Hint: update this variable with hack/gen-modules-map-resources.sh
#
# Packages only available on Fedora (not RHEL/AlmaLinux/CentOS) are in
# vars/fedora.yml instead.
__run_nginx_modules_map_resources:
  http_image_filter:
    conf_files:
      - name: "mod-http-image-filter.conf"
        type: "symlink"
        target: "/usr/share/nginx/modules/mod-http-image-filter.conf"
    packages:
      - "nginx-mod-http-image-filter"
  http_perl:
    conf_files:
      - name: "mod-http-perl.conf"
        type: "symlink"
        target: "/usr/share/nginx/modules/mod-http-perl.conf"
    packages:
      - "nginx-mod-http-perl"
  http_xslt_filter:
    conf_files:
      - name: "mod-http-xslt-filter.conf"
        type: "symlink"
        target: "/usr/share/nginx/modules/mod-http-xslt-filter.conf"
    packages:
      - "nginx-mod-http-xslt-filter"
  mail:
    conf_files:
      - name: "mod-mail.conf"
        type: "symlink"
        target: "/usr/share/nginx/modules/mod-mail.conf"
    packages:
      - "nginx-mod-mail"
  stream:
    conf_files:
      - name: "mod-stream.conf"
        type: "symlink"
        target: "/usr/share/nginx/modules/mod-stream.conf"
    packages:
      - "nginx-mod-stream"
