# Uninstall: Manage basic resource removal, such as packages or service users.

---

- name: "Setup | Uninstall | Gather service facts"
  ansible.builtin.service_facts:


- name: "Setup | Uninstall | Stop and disable service (best-effort): {{ __run_nginx_nginx_servicename }}"
  ansible.builtin.systemd_service:
    name: "{{ __run_nginx_nginx_servicename }}"
    state: "stopped"
    enabled: false
  failed_when: false # best-effort service stop
  when:
    - __run_nginx_nginx_servicename in ansible_facts['services']


- name: "Setup | Uninstall | Remove drop-in config files (snippets, sites)"
  ansible.builtin.file:
    path: "{{ item }}"
    state: "absent"
  vars:
    __run_nginx_paths_to_remove: >-
      {{
        (
          (
            (run_nginx_sites_config | default([]))
            | ansible.builtin.map(attribute='name')
            | ansible.builtin.map('ansible.builtin.regex_replace', '$', '.conf')
            | ansible.builtin.list
          )
          +
          (
            (
                query('ansible.builtin.fileglob', 'templates/snippets/*.conf.j2')
              + query('ansible.builtin.fileglob', 'templates/snippets/http/*.conf.j2')
              + query('ansible.builtin.fileglob', 'templates/snippets/location/*.conf.j2')
              + query('ansible.builtin.fileglob', 'templates/snippets/server/*.conf.j2')
            )
            | ansible.builtin.map('ansible.builtin.basename')
            | ansible.builtin.map('ansible.builtin.regex_replace', '\.j2$', '')
            | ansible.builtin.list
          )
          +
          [
            __run_nginx_config_service_file_path,
            __run_nginx_config_service_dropin_snippets_http_dir_path,
            __run_nginx_config_service_dropin_snippets_location_dir_path,
            __run_nginx_config_service_dropin_snippets_server_dir_path
          ]
        ) | ansible.builtin.unique
      }}
  when:
    - __run_nginx_paths_to_remove | ansible.builtin.length > 0
  loop: "{{ __run_nginx_paths_to_remove }}"


- name: "Setup | Uninstall | Remove snippets directory (non-Debian platforms)"
  ansible.builtin.file:
    path: "{{ __run_nginx_config_service_dropin_snippets_dir_path }}"
    state: "absent"
  when:
    - ansible_facts['os_family'] != 'Debian'


- name: "Setup | Uninstall | Remove sites directories (non-Debian/SUSE platforms)"
  ansible.builtin.file:
    path: "{{ item }}"
    state: "absent"
  when:
    - ansible_facts['os_family'] not in ['Debian', 'Suse']
  loop:
    - "{{ __run_nginx_config_service_dropin_sites_available_dir_path }}"
    - "{{ __run_nginx_config_service_dropin_sites_enabled_dir_path }}"


- name: "Setup | Uninstall | Check if platform's original nginx.conf backup exists"
  ansible.builtin.stat:
    path: "{{ __run_nginx_config_service_file_distbackup_path }}"
  register: __run_nginx_distbackup_stat


- name: "Setup | Uninstall | Restore platform's original nginx.conf from backup"
  when:
    - __run_nginx_distbackup_stat['stat']['exists']
  block:
    - name: "Setup | Uninstall | Restore nginx.conf from backup file"
      ansible.builtin.copy:
        src: "{{ __run_nginx_config_service_file_distbackup_path }}"
        dest: "{{ __run_nginx_config_service_file_path }}"
        owner: "{{ __run_nginx_config_service_file_owner }}"
        group: "{{ __run_nginx_config_service_file_group }}"
        mode: "{{ __run_nginx_config_service_file_mode }}"
        remote_src: true

    - name: "Setup | Uninstall | Remove backup notice comment from restored nginx.conf"
      ansible.builtin.lineinfile:
        path: "{{ __run_nginx_config_service_file_path }}"
        line: "{{ __run_nginx_config_service_file_distbackup_comment }}"
        state: "absent"

    - name: "Setup | Uninstall | Remove the nginx.conf backup file"
      ansible.builtin.file:
        path: "{{ __run_nginx_config_service_file_distbackup_path }}"
        state: "absent"


- name: "Setup | Uninstall | Remove module config directory (modules-enabled)"
  ansible.builtin.file:
    path: "{{ __run_nginx_config_service_dropin_modules_enabled_dir_path }}"
    state: "absent"
  when:
    - ansible_facts['os_family'] != 'Debian'


- name: "Setup | Uninstall | Remove /etc/nginx/modules symlink (non-Debian platforms)"
  ansible.builtin.file:
    path: "/etc/nginx/modules"
    state: "absent"
  when:
    - ansible_facts['os_family'] != 'Debian'


- name: "Setup | Uninstall | Remove packages"
  ansible.builtin.package:
    name: "{{ __run_nginx_packages_uninstall }}"
    state: "absent"
  when:
    - __run_nginx_packages_uninstall is ansible.builtin.defined
    - (__run_nginx_packages_uninstall | ansible.builtin.length) > 0
