# Default variables and values for this role.
#
# These variables are designed to be easily overridden (as they have a low
# precedence) and typically allow users to customize the role's behavior.
# Each variable should have a clear comment above it, describing its purpose
# and how it fits into the role's functionality.

---

# String. Determines whether the managed resources should be "present" or
# "absent". Defaults to "present". Possible values:
#
# - "present": Ensures that required components, such as software packages,
#   are installed and configured.
# - "absent": Reverts changes as much as possible, such as removing packages,
#   deleting created users, stopping services, restoring modified settings, …
run_nginx_state: "present"


# Boolean. If set to true, all managed packages will be upgraded during each
# Ansible run (e.g., when the package provider detects a newer version than
# the currently installed one). Defaults to false.
run_nginx_autoupgrade: false


# String. Defines the status of the service(s). Defaults to "enabled".
# Possible values:
#
# - "enabled": Service is running and will start automatically at boot.
# - "disabled": Service is stopped and will not start automatically at boot.
# - "running": Service is running but will not start automatically at boot.
#   This can be used to start a service on the first Ansible run without
#   enabling it for boot.
# - "unmanaged": Service will not start at boot, and Ansible will not
#   manage its running state. This is primarily useful when services are
#   monitored and managed by systems other than Ansible.
#
# The singular form ("service") is used for simplicity. However, the defined
# status applies to all services if multiple are being managed by this role.
run_nginx_service_state: "enabled"

run_nginx_sites_defaultserver_manage: true

run_nginx_main_config_block: ""

run_nginx_events_config_block: ""

run_nginx_http_config_block: ""

run_nginx_main_config_baseline_manage: true

run_nginx_events_config_baseline_manage: true

run_nginx_http_config_baseline_manage: true

run_nginx_sites_config: []

run_nginx_sites_delete_unmanaged: true

run_nginx_snippets_manage: true

run_nginx_snippets_delete_unmanaged: false

run_nginx_snippet_settings: {}

run_nginx_modules_enabled: [] # FIXME not handled / implemented yet

run_nginx_modules_disabled: [] # FIXME not handled / implemented yet
